coverage:
  status:
    project:
      default: off
      restserver:
        target: 90%
        flags: restserver
      wakaama:
        flags: wakaama
    patch: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  restserver:
    paths:
      - examples/restserver/
  wakaama:
    paths:
      - core/
      - examples/shared/
