language: c

sudo: false
dist: trusty

compiler: 
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmicrohttpd-dev libjansson-dev libb64-dev
#  - sudo apt-get install -y libcurl4-gnutls-dev libgnutls28-dev libgcrypt20-dev

install:
  - ./.travis/install_ulfius.sh

before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

script:
  - ./scripts/build.sh
  - ./scripts/test.sh
