# Provides HTTP_FRAMEWORK_SOURCES_DIR, HTTP_FRAMEWORK_SOURCES and HTTP_FRAMEWORK_LIBRARIES variables.

set(HTTP_FRAMEWORK_SOURCES_DIR ${CMAKE_CURRENT_LIST_DIR}/src)
set(HTTP_FRAMEWORK_SOURCES
    ${HTTP_FRAMEWORK_SOURCES_DIR}/ulfius_http_framework.cpp
    )

find_library(ULFIUS_LIB ulfius)

set (HTTP_FRAMEWORK_LIBRARIES ${ULFIUS_LIB})
